CREATE TABLE DEPARTAMENTO(
	CODIGO_DEPTO NUMBER NOT NULL, 
	NOMBRE_DEPTO VARCHAR(100), 
	CONSTRAINT DEPTA_PK PRIMARY KEY (CODIGO_DEPTO)
) TABLESPACE ELECCIONESTBS ;

-- DROP TABLE DEPARTAMENTO ;

SELECT  * FROM DEPARTAMENTO ;

CREATE TABLE MUNICIPIO(
	CODIGO_MUNI NUMBER NOT NULL, 
	DEPTO_MUNI NUMBER NOT NULL, 
	NOMBRE_MUNI VARCHAR(100), 
	CONSTRAINT MUNI_PK PRIMARY KEY (CODIGO_MUNI, DEPTO_MUNI),
	CONSTRAINT DEPTO_MUNI_FK
    FOREIGN KEY (DEPTO_MUNI)
    REFERENCES DEPARTAMENTO(CODIGO_DEPTO)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE MUNICIPIO;

SELECT  * FROM MUNICIPIO ;

CREATE TABLE PARTIDO(
	CODIGO_PART NUMBER NOT NULL, 
	NOMBRE_PART VARCHAR(100), 
	CONSTRAINT PART_PK PRIMARY KEY (CODIGO_PART)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE PARTIDO;

SELECT * FROM PARTIDO;

CREATE  TABLE ELECCION(
	CODIGO_ELE NUMBER NOT NULL, 
	NOMBRE_ELE VARCHAR(100), 
	CONSTRAINT ELE_PK PRIMARY KEY (CODIGO_ELE)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE ELECCION;

SELECT  * FROM ELECCION ;

CREATE TABLE ACTA(
	NUMERO_MESA NUMBER NOT NULL, 
	TIPO_ELECCION NUMBER NOT NULL, 
	DEPARTAMENTO NUMBER NOT NULL,
	MUNICIPIO NUMBER NOT NULL, 
	PAPELETAS_RECIBIDAS NUMBER, 
	TOTAL_VOTOS_VALIDOS NUMBER, 
	VOTOS_NULOS NUMBER, 
	VOTOS_BLANCO NUMBER, 
	VOTOS_VALIDOS_EMITIDOS  NUMBER,
	VOTOS_INVALIDOS NUMBER, 
	IMAGEN BLOB, 
	ESTADO_IMAGEN VARCHAR(3), -- VAL, ANU, ACT
	CUADRA_ACTA VARCHAR(1), -- S o N 
	CONTEO_IMPUGNA NUMBER, 
	CONTEO_INSCRITOS NUMBER, 
	STACTA VARCHAR(3), -- VAL, ANU, ACT
	STESCAN VARCHAR(3), 
	STSFISIC VARCHAR(3), 
	STSTRANS VARCHAR(3), 
	CONSTRAINT ACTA_PK PRIMARY KEY (NUMERO_MESA, TIPO_ELECCION),
	
	CONSTRAINT DEPTO_ACTA_FK
    FOREIGN KEY (DEPARTAMENTO, MUNICIPIO)
    REFERENCES MUNICIPIO(DEPTO_MUNI, CODIGO_MUNI), 
    
	CONSTRAINT ELE_ACTA_FK
    FOREIGN KEY (TIPO_ELECCION)
    REFERENCES ELECCION(CODIGO_ELE)
	
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE ACTA;

SELECT  * FROM ACTA;

CREATE TABLE VOTO(
	VOTO_PARTIDO NUMBER NOT NULL, 
	VOTO_MESA NUMBER NOT NULL, 
	VOTO_ELECCION NUMBER NOT NULL, 
	VOTO_CANTIDAD NUMBER, 
	CONSTRAINT VOTO_PK PRIMARY KEY (VOTO_PARTIDO, VOTO_MESA, VOTO_ELECCION),
	
	CONSTRAINT PARTIDO_VOTO_FK
    FOREIGN KEY (VOTO_PARTIDO)
    REFERENCES PARTIDO(CODIGO_PART), 
    
	CONSTRAINT ACTA_VOTO_FK
    FOREIGN KEY (VOTO_MESA, VOTO_ELECCION)
    REFERENCES ACTA(NUMERO_MESA, TIPO_ELECCION)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE VOTO:

SELECT * FROM ACTA;